name: Update Citation Files

on:
  push:
    paths:
      - "DESCRIPTION"
  workflow_dispatch:

jobs:
  update-citation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install minimal system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("cffr", "desc"))'

      - name: Update inst/CITATION
              - name: Update inst/CITATION
        run: |
          Rscript -e '
            library(desc)

            d <- desc::desc(file = "DESCRIPTION")
            title <- d$get("Title")
            version <- d$get("Version")
            urls <- strsplit(d$get("URL"), ",")[[1]]
            url <- trimws(urls[1])
            year <- format(Sys.Date(), "%Y")

            # Get Authors@R as text
            authors <- d$get_field("Authors@R")

            citation_lines <- c(
              "citHeader(\"To cite this package, use:\")",
              "",
              "bibentry(",
              "  bibtype = \"Manual\",",
              sprintf("  title = \"%s\",", title),
              "  author = ",  # no comma
              paste0("    ", authors, ","),
              sprintf("  year = \"%s\",", year),
              sprintf("  note = \"R package version %s\",", version),
              sprintf("  url = \"%s\"", url),
              ")"
            )

            writeLines(citation_lines, con = "inst/CITATION")
          '


      - name: Update CITATION.cff
        run: |
          Rscript -e 'cffr::cff_write()'

      - name: Commit and Push if Changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add inst/CITATION CITATION.cff
          git commit -m "Auto-update citation files" || echo "No changes to commit"
          git push
